### ISSUE TITLE
Error on node version 6.3.0

### ISSUE THREAD

**Issue by erickponce** [marcominetti/node-memwatch#19]
Error: Module version mismatch. Expected 48, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

npm uninstall, rebuild and install again but its not working

**Comment by srowatt** [comment]
The major version of node used to build memwatch is a different major version of node you're using memwatch with.

In this case, it looks like memwatch was built against node v4+ but you're trying to use it with node v0.12. Try doing an `npm rebuild` to rebuild memwatch against the current version of node.
