### ISSUE TITLE
can't able to compile on node v5.8.0

### ISSUE THREAD

**Issue by VenkatNivaata** [marcominetti/node-memwatch#20]
> memwatch-next@0.3.0 install /home/ubuntu/stage/app/node_modules/memwatch-next
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/opt/node/lib/node_modules/npm/node_modules/which/which.js:63:19)
gyp ERR! stack     at E (/opt/node/lib/node_modules/npm/node_modules/which/which.js:72:29)
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/which/which.js:81:16
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.13.0-74-generic
gyp ERR! command "/opt/node/bin/node" "/opt/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/stage/carpool2/node_modules/memwatch-next
gyp ERR! node -v v5.8.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/opt/node/bin/node" "/usr/local/bin/npm" "install" "memwatch-next" "--save"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! memwatch-next@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memwatch-next@0.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the memwatch-next package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs memwatch-next
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls memwatch-next
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/stage/carpool2/npm-debug.log

**Comment by srowatt** [comment]
Looks like you don't have **make** installed to build the C library. Try this first:
`sudo apt-get install build-essential`
