### ISSUE TITLE
bindings.js:83   Uncaught Error: Module version mismatch. Expected 50, got 48

### ISSUE THREAD

**Issue by nphias** [marcominetti/node-memwatch#22]
node version : 6.8.1 (same error for LTS version)
mac osx: 10.11 (el capitan)
xcode 8 installed
framework: (electron)

tried reinstall etc..

memwatch-next@0.3.0 install ../node_modules/memwatch-next
> node-gyp rebuild

  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
  CXX(target) Release/obj.target/memwatch/src/init.o
../src/init.cc:20:17: warning: 'AddGCEpilogueCallback' is deprecated
      [-Wdeprecated-declarations]
        v8::V8::AddGCEpilogueCallback(memwatch::after_gc);
                ^
/Users/x/.node-gyp/6.8.1/include/node/v8.h:6475:12: note: 
      'AddGCEpilogueCallback' has been explicitly marked deprecated here
      void AddGCEpilogueCallback(GCCallback callback,
           ^
1 warning generated.
  CXX(target) Release/obj.target/memwatch/src/memwatch.o
  CXX(target) Release/obj.target/memwatch/src/util.o
  SOLINK_MODULE(target) Release/memwatch.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

code:  var memwatch = require('memwatch-next');

**Comment by Nomia** [comment]
Same error here:
init.js:136 Error: Module version mismatch. Expected 50, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:178:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/xxx/Desktop/wxbot-node/node_modules/memwatch-next/node_modules/bindings/bindings.js:76:44)(anonymous function) @ init.js:136
