### ISSUE TITLE
can't install on node 8.x

### ISSUE THREAD

**Issue by mkozjak** [marcominetti/node-memwatch#32]
node -v
v8.1.1

> memwatch-next@0.3.0 install /opt/dev/uniqcast/tvmid/core/node_modules/memwatch-next
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.1.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.13\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.1.1
gyp verb command install [ '8.1.1' ]
gyp verb install input version string "8.1.1"
gyp verb install installing version: 8.1.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.1.1
gyp verb ensuring nodedir is created /Users/mkozjak/.node-gyp/8.1.1
gyp verb created nodedir /Users/mkozjak/.node-gyp/8.1.1
gyp http GET https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
gyp http 404 https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.1.1' ]
gyp verb remove using node-gyp dir: /Users/mkozjak/.node-gyp
gyp verb remove removing target version: 8.1.1
gyp verb remove removing development files for version: 8.1.1
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:120:20)
gyp ERR! stack     at Request.emit (events.js:210:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1074:10)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:564:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:453:20)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/dev/uniqcast/tvmid/core/node_modules/memwatch-next
gyp ERR! node -v v8.1.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memwatch-next@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the memwatch-next@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Santinell** [comment]
Node.js v8.2.1 and I have no problem with installing, try to update nodejs to latest version

**Comment by Santinell** [comment]
And looks like problem was with downloading file
 https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz

Maybe it was a temporary network problem also.

**Comment by xgretsch** [comment]
I've installed fine on node v8.1.4 on OS X.
I am unable to install on v8.8.1 on Ubuntu 16.04.

So I don't think it's a simple version problem.
Although this looks from the log like a permissions problem, I have made sure that permissions are wide open. I believe that the reason the system can't mkdir `/datadrive/planal/node_modules/memwatch-next/build` is that the parent directory `/datadrive/planal/node_modules/memwatch-next` does not exist.

```
$ sudo npm install memwatch-next

> memwatch-next@0.3.0 install /datadrive/planal/node_modules/memwatch-next
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/datadrive/planal/node_modules/memwatch-next/build'
gyp ERR! System Linux 4.11.0-1013-azure
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /datadrive/planal/node_modules/memwatch-next
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN testNode@1.0.0 No description
npm WARN testNode@1.0.0 No repository field.
npm WARN testNode@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memwatch-next@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the memwatch-next@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/planal/.npm/_logs/2017-11-08T16_00_41_783Z-debug.log
```

**Comment by shukriadams** [comment]
+1
