### ISSUE TITLE
Install failure on osx Mojave

### ISSUE THREAD

**Issue by ran-eh** [marcominetti/node-memwatch#44]
`npm i node-memwath` fails on a mac.  Also see https://stackoverflow.com/questions/54236951/node-10-node-gyp-rebuild-error-during-npm-install.

```make: *** [Release/obj.target/memwatch/src/init.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/11.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/reh/src/fix-client-server/node_modules/memwatch-next
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memwatch-next@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memwatch-next@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/reh/.npm/_logs/2019-01-18T22_32_21_058Z-debug.log
(reverse-i-search)`no': npm install -g node-gyp```

**Comment by morleytatro** [comment]
Same here on Node 10.15.0. Really sucks because I'm trying to track down a nasty memory leak!

**Comment by vasiliyb** [comment]
Same here on all versions of node i've tried.

**Comment by mitchconquer** [comment]
For me I ran code below and it worked. No idea why that was necessary since it was already installed but.... ¯\_(ツ)_/¯

```bash
xcode-select --install
```
