### ISSUE TITLE
cannot install on node v11.8.0

### ISSUE THREAD

**Issue by huangqibin** [marcominetti/node-memwatch#45]
npm install memwatch-next

> memwatch-next@0.3.0 install /Users/apple/.nvm/node_modules/memwatch-next
> node-gyp rebuild

  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
../src/heapdiff.cc:95:35: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        String::Utf8Value utfString(str->ToString());
                                         ^
/Users/apple/.node-gyp/11.8.0/include/node/v8.h:2548:10: note: 'ToString' has
      been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/apple/.node-gyp/11.8.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/heapdiff.cc:95:20: warning: 'Utf8Value' is deprecated: Use Isolate
      version [-Wdeprecated-declarations]
        String::Utf8Value utfString(str->ToString());
                          ^
/Users/apple/.node-gyp/11.8.0/include/node/v8.h:2991:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/apple/.node-gyp/11.8.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
2 warnings generated.
  CXX(target) Release/obj.target/memwatch/src/init.o
../src/init.cc:20:9: error: no type named 'AddGCEpilogueCallback' in 'v8::V8';
      did you mean 'Nan::GCEpilogueCallback'?
        v8::V8::AddGCEpilogueCallback(memwatch::after_gc);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Nan::GCEpilogueCallback
../../nan/nan.h:745:35: note: 'Nan::GCEpilogueCallback' declared here
  typedef v8::Isolate::GCCallback GCEpilogueCallback;
                                  ^
../src/init.cc:20:49: error: definition or redeclaration of 'after_gc' not
      allowed inside a function
        v8::V8::AddGCEpilogueCallback(memwatch::after_gc);
                                      ~~~~~~~~~~^
2 errors generated.
make: *** [Release/obj.target/memwatch/src/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/apple/.nvm/node_modules/memwatch-next
gyp ERR! node -v v11.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memwatch-next@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the memwatch-next@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2019-01-28T06_57_42_231Z-debug.log

**Comment by Homer1011110** [comment]
I met this problem on node v10.14.0.

**Comment by IslamWahid** [comment]
same here with node v10.15.1

**Comment by jsilvia721** [comment]
Also seeing this issue with node v10.10.0

**Comment by Zakharen** [comment]
same issue...
anyway, successfully installed on node v8.15.1 (don't forget to remove node_modules before), after I tried different node versions

**Comment by kylealwyn** [comment]
Same issue on Node 10.15.0 with same logs. Please let me know if I can provide anything else useful

**Comment by Stono** [comment]
I do not see this on:
```
Versions:
  - Node: v10.15.3
  - NPM:  6.9.0
  - Yarn: 1.15.2
  - Base: 26
```

**Comment by Selhar** [comment]
Also having this issue on node `11.14.0`

**Comment by kingces95** [comment]
Hm. Is this tool still being maintained or should we start exploring fixing this ourselves?

**Comment by ksteckert** [comment]
This issue may be resolved in the fork mentioned in issue #42 (v9+ support).  Worth a try.

Here's a link to [node-memwatch](https://www.npmjs.com/package/node-memwatch), a v9+ fork of memwatch-next.
Just update your code to require `node-memwatch` instead of `memwatch-next`

**Comment by 100001** [comment]
Also on Node v12.12.0

**Comment by RMann90** [comment]
Same issue on Node v12.13.0

The suggestion by @ksteckert did not work

**Comment by suhanw** [comment]
Same issue on Node v12.14.0

**Comment by ShanMadane** [comment]
Not working on 13.3.0
