### ISSUE TITLE
cannot install on MacOS

### ISSUE THREAD

**Issue by handsomeBingo** [marcominetti/node-memwatch#52]
errors as following:
> node-gyp rebuild

  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
In file included from ../src/heapdiff.cc:12:
../src/heapdiff.hh:18:38: error: no template named 'Handle' in namespace 'v8'
        static void Initialize ( v8::Handle<v8::Object> target );
                                 ~~~~^
../src/heapdiff.cc:46:21: error: variable has incomplete type 'void'
heapdiff::HeapDiff::Initialize ( v8::Handle<v8::Object> target )
                    ^
../src/heapdiff.cc:46:55: error: expected '(' for function-style cast or type
      construction
heapdiff::HeapDiff::Initialize ( v8::Handle<v8::Object> target )
                                            ~~~~~~~~~~^
../src/heapdiff.cc:46:38: error: no member named 'Handle' in namespace 'v8'
heapdiff::HeapDiff::Initialize ( v8::Handle<v8::Object> target )
                                 ~~~~^
../src/heapdiff.cc:46:57: error: use of undeclared identifier 'target'
heapdiff::HeapDiff::Initialize ( v8::Handle<v8::Object> target )
                                                        ^
../src/heapdiff.cc:46:65: error: expected ';' after top level declarator
heapdiff::HeapDiff::Initialize ( v8::Handle<v8::Object> target )
                                                                ^
                                                                ;
../src/heapdiff.cc:132:14: error: unknown type name 'idset'
void setDiff(idset a, idset b, vector<uint64_t> &c)
             ^
../src/heapdiff.cc:132:23: error: unknown type name 'idset'
void setDiff(idset a, idset b, vector<uint64_t> &c)
                      ^
../src/heapdiff.cc:134:10: error: use of undeclared identifier 'idset'
    for (idset::iterator i = a.begin(); i != a.end(); i++) {
         ^
../src/heapdiff.cc:134:17: error: use of class template 'iterator' requires
      template arguments
    for (idset::iterator i = a.begin(); i != a.end(); i++) {
                ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:627:29: note:
      template is declared here
struct _LIBCPP_TEMPLATE_VIS iterator
                            ^
../src/heapdiff.cc:182:25: error: use of undeclared identifier 'handleToStr'
            type.append(handleToStr(node->GetName()));
                        ^
../src/heapdiff.cc:223:8: error: no template named 'Handle'
static Handle<Value> changesetToObject(changeset & changes)
       ^
../src/heapdiff.cc:230:12: error: no matching member function for call to 'Set'
        d->Set(Nan::New("what").ToLocalChecked(), Nan::New(i->first.c_str...
        ~~~^~~
/Users/didi/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/didi/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/heapdiff.cc:231:12: error: no matching member function for call to 'Set'
        d->Set(Nan::New("size_bytes").ToLocalChecked(), Nan::New<v8::Numb...
        ~~~^~~
/Users/didi/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/didi/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/heapdiff.cc:232:12: error: no matching member function for call to 'Set'
        d->Set(Nan::New("size").ToLocalChecked(), Nan::New(mw_util::niceS...
        ~~~^~~
/Users/didi/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/didi/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/heapdiff.cc:233:12: error: no matching member function for call to 'Set'
        d->Set(Nan::New("+").ToLocalChecked(), Nan::New<v8::Number>(i->se...
        ~~~^~~
/Users/didi/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/didi/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/heapdiff.cc:234:12: error: no matching member function for call to 'Set'
        d->Set(Nan::New("-").ToLocalChecked(), Nan::New<v8::Number>(i->se...
        ~~~^~~
/Users/didi/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/didi/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/heapdiff.cc:235:12: error: no matching member function for call to 'Set'
        a->Set(a->Length(), d);
        ~~~^~~
/Users/didi/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3670:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/didi/Library/Caches/node-gyp/14.8.0/include/node/v8.h:3673:37: note:
      candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/heapdiff.cc:238:12: error: no viable conversion from returned value of
      type 'v8::Local<Array>' to function return type 'int'
    return scope.Escape(a);
           ^~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/memwatch/src/heapdiff.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/didi/Documents/mabin/bingo/auto-t/node_modules/memwatch-next
gyp ERR! node -v v14.8.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN auto-t@1.0.0 No description
npm WARN auto-t@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memwatch-next@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memwatch-next@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by dancornilov** [comment]
Hey, I have the similar issue, does anyone found the problem?

**Comment by davesagraf** [comment]
@handsomeBingo @dancornilov 

I've had a similar issue and have just found this [@airbnb/node-memwatch](https://www.npmjs.com/package/@airbnb/node-memwatch) npm module and its corresponding [@types/airbnb__node-memwatch](https://www.npmjs.com/package/@types/airbnb__node-memwatch) types (have checked it's working both with Node v18.18.2 and Node v22.15.0)

Also, this project is actually a fork of this original project [node-memwatch](https://github.com/lloyd/node-memwatch) (but it's quite old and won't likely work properly with the latest versions of Node.js)
